### ISSUE TITLE
Sprites as 2d object in 3d view

### ISSUE THREAD

**Issue by Trusiak** [enable3d/enable3d#38] opened 2020-08-12 13:50 UTC
Hello, im using phaser3 extension.

Is there any way to integrate sprites with 3d dimenstion (like in three.js)?

https://threejs.org/examples/?q=sprite#webgl_sprites_nodes

i know, that theoretically we could use THREE.js native code, but phaser / enable3D API is more comfortable, and provides new possibilities ^^

**Comment by yandeu** [comment] 2020-08-12 14:10
You can use Enable3d with or without Phaser. In both cases, you have access to three.js. Means, you should be able to make every three.js example work.

Like in [this example](https://enable3d.io/examples/standalone-mode.html), you can import THREE from ENABLE3D.

Hope this helps :)

**Comment by Trusiak** [comment] 2020-08-13 14:29
but the idea of this library is to make it easier to create a 3d game, and you did it brilliantly :)

**Comment by yandeu** [comment] 2020-08-14 09:50
🤣🤣🤣 You're right! Thanks :)

At the moment I do not have much time to work on enable3d. But it's my favorite project. I surely will to add more features in the future.

**Comment by lodossDev** [comment] 2021-02-04 08:27
Hi I second this, i really want my sprites in 3d space, i am trying to make a scrolling beat em up game and need 3d physics.

Is there a way to do this using phaser?

**Comment by yandeu** [comment] 2021-02-04 12:44
Does [this example](https://enable3d.io/examples/sync-3d-to-2d.html) help?

**Comment by lodossDev** [comment] 2021-02-04 16:08
Hi thanks Yannick, the above example is not really what I expect, the idea is having a sprite which acts like a 3d object in x, y, z. So I should see a sprite somewhere on the plane, separate from the box and not bound by the camera, or the camera bound on the sprite.

My idea is also to put the camera in orthographic mode to get that 2d view for my 3d world with sprites.

Any help around this would be great.

**Comment by yandeu** [comment] 2021-02-04 17:07
I just made [a new example](https://enable3d.io/examples/texture-on-a-plane.html). Does this help?

**Comment by lodossDev** [comment] 2021-02-04 20:07
Hi Yannick,

What I am thinking is how would you get this sprite into the 3d world:

https://www.google.com/url?sa=i&url=https%3A%2F%2Fmugenguild.com%2Fforum%2Ftopics%2Fsfiii-hidef-sprites-apng-versions-added-139727.0.html&psig=AOvVaw0oB341A-pLnWXVAdc78CBq&ust=1612555525636000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKju-52D0e4CFQAAAAAdAAAAABAD

Would you really create plane meshes to achieve this?

**Comment by yandeu** [comment] 2021-02-04 20:45
Oh, you mean just a simple 2d sprite sheet like [this](https://felixmariotto.github.io/from_indexed_texture)?
Just like in phaser but you need it in three.js?

**Comment by lodossDev** [comment] 2021-02-04 20:49
that is correct, but i also want to move it in 3d space :)

**Comment by yandeu** [comment] 2021-02-04 21:00
I will try to implement it.

**Comment by yandeu** [comment] 2021-02-04 23:57
I just wrote a simple sprite mixer and published it to the [sprite-mixer branch](https://github.com/enable3d/enable3d/tree/sprite-mixer).

Check it out with `npm i` and `npm start`.

Also, check out the 2 files [threeScene.ts](https://github.com/enable3d/enable3d/blob/sprite-mixer/packages/dev/src/threeScene.ts) and [spriteMixer.ts](https://github.com/enable3d/enable3d/blob/sprite-mixer/packages/threeGraphics/src/plugins/spriteMixer.ts).

Feel free to improve it!

**Comment by lodossDev** [comment] 2021-02-05 20:02
this is awesome, exactly what I was looking for, one thing how do I disable the smoothing on the sprite/texture?

**Comment by yandeu** [comment] 2021-02-05 20:30
Yes, it is `NearestFilter` for pixel-art. I have added it to the latest commit.
```ts
texture.magFilter = NearestFilter
texture.minFilter = NearestFilter
```

---

@Trusiak, does this also solve your initial request?

**Comment by Trusiak** [comment] 2021-02-07 11:37
At first glance looks good, but phaser sprite mixer have implemented additional features like "read spritesheet data from .json file"- it's nessesary in huge projects. 
For some reason, three.js mixer ruin quality of sprite sheet's in 3d space (don't know why it's happend).

**Comment by yandeu** [comment] 2021-02-07 16:17
> read spritesheet data from .json file

I think I will add this as well. (_in the future_)

> ruin quality of sprite sheet's

Have you tried to adjust the Magnification and Minification Filter? Just like in my previous comment.
Also see:
- https://threejs.org/docs/#api/en/textures/Texture
- https://threejs.org/docs/#api/en/constants/Textures
- https://stackoverflow.com/questions/16709392

**Comment by Trusiak** [comment] 2021-02-07 20:40
okay, when this feature will be avaliable on main production?

**Comment by yandeu** [comment] 2021-02-07 21:38
- without .json files: next version
- with .json files: unknown

**Comment by Trusiak** [comment] 2021-02-08 07:06
`

> without .json files: next version

`
I figured :smile_cat: the question is: when are you going to release next version?

**Comment by lodossDev** [comment] 2021-02-08 08:59
@Trusiak please don't put pressure on Tannick, he is doing this in his own time, and building this awesome library, so please be patient. 

If you really want to use atlas sprite sheets, maybe look at babylonjs:
https://doc.babylonjs.com/divingDeeper/sprites/sprites_introduction

**Comment by yandeu** [comment] 2021-02-08 12:57
> I figured  the question is: when are you going to release next version?

The upgrade to three.js r125 was difficult. They completely removed all non-bufferGeometries. I will merge the ActionSprite class, make some polishing and release v22 at the end of this week.

---

I will close this issue for now.

If you want to talk more about the implementation of .json Atlas, feel free to join the [discussions](https://github.com/enable3d/enable3d/discussions).

_I have limited [new issues](https://github.com/enable3d/enable3d/issues/new/choose) to bug reports only._

**Closed by yandeu** 2021-02-08 12:57 UTC
Labels: enhancement

**Comment by yandeu** [comment] 2021-02-11 15:46
I'm about to add support for TextureAtlas.
The release delays therefore until next week.

**Comment by yandeu** [comment] 2021-02-12 14:16
- Just added support for buttons (just like [here](https://phaser.io/examples/v2/buttons/action-on-click)).
- Will also add text support like [here](https://phaser.io/examples/v2/text/hello-arial)
- and 2d shapes like [here](https://phaser.io/examples/v2/geometry/polygon).

**Comment by yandeu** [comment] 2021-02-18 14:21
Done! The examples are on the [website](https://enable3d.io/examples.html).

It is still experimental. 

To load it from npm, use the tag `dev`. For example: `npm install @enable3d/ammo-physics@dev`.

**Comment by lodossDev** [comment] 2021-02-18 14:35
Yannick, i think we also need a way to load a single or array of images as
part of the animated class, i usually don’t bother with sprite sheets and
like them as individual images.

**Comment by yandeu** [comment] 2021-02-18 14:45
> don’t bother with sprite sheets and like them as individual images

This is not good practice. See [Batch draw calls](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#batch_draw_calls_prefer_fewer-but-larger_draw_calls).

If I have the choice to give a performance boost by design, I will do it.  Therefore I will not support individual images.

Consider trying [free-sprite-sheet-packer](https://www.codeandweb.com/free-sprite-sheet-packer).

**Comment by lodossDev** [comment] 2021-02-21 14:45
Yannick, question does rotating sprites work, I tried rotating 35 deg but
it does not seem to affect the sprite?

**Comment by yandeu** [comment] 2021-02-21 14:54
You should be able to use these functions on a sprite:
```ts
setPosition(x: number, y: number)
setDepth(z: number)
setRotation(rotation: number)
getRotation()
setScale(x: number, y?: number)
```

**Comment by lodossDev** [comment] 2021-02-22 23:20
Hi Yannick,

Going back to the array of images for sprite, it's a flow and an
alternative way for animation less performance/memory constraints:

here is a class i created for this, and wanted you insight towards the
solution:

import { Texture, Sprite, SpriteMaterial, Vector3 } from
'@enable3d/three-wrapper/dist'
import { EventEmitter } from 'eventemitter3'
import { ThreeGraphics } from '..';

export class ImageSprite extends Sprite {
private images: Array<Texture>;
private currentFrame: number = 0;
private interval: number;
private rate: number = 10;

constructor() {
super();

this.images = [];
this.currentFrame = 0;
}

addImage(texture: Texture) {
this.images.push(texture);
}

addImages(textures: Array<Texture>) {
this.images = [...textures];
}

update() {
if (!this.images || this.images.length == 0) {
console.warn(`No images defined for this sprite.`);
return ;
}
this.material.map = this.images[this.currentFrame];
const playNextFrame = () => {
this.currentFrame++;
this.material.map = this.images[this.currentFrame];
console.log('ryu frame: ' + this.currentFrame);

if (this.currentFrame >= this.images.length) {
this.currentFrame = 0
}
};

this.interval = window.setInterval(() => {
playNextFrame();
}, 1000 / this.rate);
}
}

**Comment by lodossDev** [comment] 2021-02-23 09:16
Hi Yannick,

Going back to the array of images for a sprite, it's a flow and an
alternative way for animation - less performance/memory constraints:

here is a class i created for this, and wanted your insight towards the
solution:

```javascript
export class ImageSprite extends Sprite {
    private images: Array<Texture>;
    private currentFrame: number = 0;
    private interval: number;
    private rate: number = 10;

    constructor() {
        super();

        this.images = [];
        this.currentFrame = 0;
    }

    addImage(texture: Texture) {
        this.images.push(texture);
    }

    addImages(textures: Array<Texture>) {
        this.images = [...textures];
    }

    update() {
        if (!this.images || this.images.length == 0) {
            console.warn(`No images defined for this sprite.`);
            return ;
        }
        
        this.material.map = this.images[this.currentFrame];
        
        const playNextFrame = () => {
            this.currentFrame++;
            this.material.map = this.images[this.currentFrame];
            console.log('ryu frame: ' + this.currentFrame);

            if (this.currentFrame >= this.images.length) {
                this.currentFrame = 0
            }
        };

        this.interval = window.setInterval(() => {
            playNextFrame();
          }, 1000 / this.rate);
    }
}
```

**Comment by yandeu** [comment] 2021-02-23 10:04
I just added the methods `getTexture()` and `setTexture()` to the `SimpleSprite` class.

You can now do this:

```ts
const frames = [] // array of textures

const sprite = new FLAT.SimpleSprite(frames[0])
sprite.setPosition(width / 2, height / 2)
this.ui.scene.add(sprite)

let currentFrame = 0

const fps = 10
setInterval(() => {
  currentFrame++
  if (currentFrame >= frames.length) currentFrame = 0
  sprite.setTexture(frames[currentFrame])
}, 1000 / fps)
```
